### Test GET all products
GET http://localhost:5000/api/products
Content-Type: application/json

###

### Test POST create a new product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Milk",
  "quantity": 5,
  "expiration": "2024-12-31"
}

###

### Test POST create another product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Bread",
  "quantity": 2,
  "expiration": "2024-12-25"
}

###

### Test POST with invalid data (should fail)
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "",
  "quantity": -1,
  "expiration": "2020-01-01"
}

###

### Test GET all products again (to see the new products)
GET http://localhost:5000/api/products
Content-Type: application/json 