### Test GET all products
GET http://localhost:5000/api/products
Content-Type: application/json

###

### Test POST create a new product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "water",
  "quantity": 5,
  "expiration": "2024-12-31",
  "size": "400g",
  "status": "green"
}

###

### Test PUT update a product
PUT http://localhost:5000/api/products/1
Content-Type: application/json

{
  "name": "milk",
  "quantity": 5,
  "expiration": "2024-12-31",
  "size": "400g",
  "status": "green"
}

### Test DELETE a product
DELETE http://localhost:5000/api/products/1
Content-Type: application/json

###

